"""
LLM Hybridizer: Uses Gemini to generate intelligent A-B hybrid alpha expressions.

The LLM is constrained by:
- Mutation rules (preserve A, use B as weak modifier)
- Feedback memory (avoid repeating failed patterns)
- WorldQuant operator vocabulary
- Proven structural templates from experience
"""

from __future__ import annotations

import json
import logging
import os
import re
import time
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger(__name__)


@dataclass
class HybridCandidate:
    """A candidate alpha generated by the LLM."""
    expression: str
    mutation_mode: str       # weak_gate / regime / corr_breaker / dataset_sub / custom
    hypothesis: str
    parent_a_expr: str
    parent_b_expr: str
    tag_pair: str
    pair_id: str
    raw_llm_response: str = ""


# ── Mutation modes (from toy_demo.py + user experience) ──────────────

MUTATION_MODES = {
    "weak_gate_hybrid": (
        "Use B as a weak gate (trade_when) while preserving A as the main signal. "
        "Example: trade_when(rank(B) > 0.55, A, -1)"
    ),
    "regime_hybrid": (
        "Use B as a regime condition: if B signals a favorable regime, "
        "use full A; otherwise reduce exposure. "
        "Example: if_else(ts_rank(B, 20) > 0.5, A, 0.5 * A)"
    ),
    "mild_corr_breaker": (
        "Use B as a mild modifier to break correlation without destroying A. "
        "Use group_neutralize to reduce sector bias. "
        "Example: group_neutralize(A * (1 + 0.1 * rank(B)), sector)"
    ),
    "yield_plus_improvement": (
        "Combine a valuation signal (A) with an improvement signal (B). "
        "Example: group_rank(ts_rank(A, 252) + 0.5 * ts_rank(ts_delta(B, 252), 126), subindustry)"
    ),
    "conditional_activation": (
        "Only activate A when B satisfies a specific condition. "
        "Different from weak_gate: the condition should be economically meaningful. "
        "Example: if_else(ts_delta(est_eps, 126) > 0, group_rank(A, subindustry), 0)"
    ),
}


# ── Core system prompt ───────────────────────────────────────────────

SYSTEM_PROMPT = """You are an expert quantitative researcher specializing in formulaic alpha discovery for WorldQuant Brain.

## Your Task
Given two parent alpha expressions (A and B), generate a hybrid child alpha that:
1. PRESERVES A's core signal as the primary driver
2. Uses B only as a WEAK modifier, gate, or regime condition
3. Produces a formula that is structurally distinct from both parents

## WorldQuant Fast Expression Operators
Available operators (use ONLY these):
- Rank: rank(x), group_rank(x, group), ts_rank(x, d)
- Time series: ts_delta(x, d), ts_mean(x, d), ts_sum(x, d), ts_std_dev(x, d), ts_decay_linear(x, d, dense=false), ts_zscore(x, d), ts_rank(x, d), ts_backfill(x, d), ts_corr(x, y, d), ts_covariance(x, y, d), ts_arg_max(x, d), ts_arg_min(x, d), ts_max(x, d), ts_min(x, d), ts_product(x, d), ts_skewness(x, d), ts_kurtosis(x, d), ts_av_diff(x, d), ts_quantile(x, d), ts_scale(x, d), ts_regression(y, x, d, lag=0, rettype=0)
- Turnover control: hump(x, hump=0.01), jump_decay(x, d, sensitivity=0.5, force=0.1), ts_target_tvr_decay(x, target_tvr=0.1)
- Group: group_rank(x, group), group_neutralize(x, group), group_zscore(x, group), group_mean(x, N, group), group_sum(x, group), group_scale(x, group)
- Conditional: if_else(cond, true_val, false_val), trade_when(cond, signal, default)
- Math: abs(x), log(x), sign(x), power(x, p), max(x, y), min(x, y), signed_power(x, p), sqrt(x)
- Transform: rank(x), scale(x), sigmoid(x), pasteurize(x), winsorize(x, std=N), normalize(x), zscore(x), quantile(x), bucket(rank(x), range="0,1,0.1")
- Utility: days_from_last_change(x), last_diff_value(x, d), vector_neut(x, y), ts_step(1)
- Groups: market, sector, industry, subindustry, densify(group_field)

## Available Data Fields
- Price: open, high, low, close, vwap, returns, volume, adv20, cap
- Fundamental (standard): operating_income, operating_cashflow_reported_value, current_ratio, return_assets, income, est_eps
- Fundamental (MDF): mdf_pva, mdf_rnd, mdf_avi, mdf_gry, mdf_opi, mdf_rds, mdf_bet, mdf_sq5, mdf_eg3, mdf_sg3, mdf_ite_q, mdf_cap, mdf_oey, mdf_eda, mdf_qe6, mdf_bkv, mdf_val, mdf_com, mdf_sic, mdf_rec
- Fundamental (FND6): fnd6_dcvt, fnd6_optvol, fnd6_newa1v1300_epspi, fnd6_newqv1300_invfgq, fnd6_newqv1300_recdq, fnd6_pnrsho, fnd6_mibn
- Analyst: est_eps, fam_est_eps_rank, fn_liab_fair_val_l1_a
- Options: implied_volatility_call_120, implied_volatility_put_120

## Critical Rules
1. NEVER create destructive A-B spreads (like A - B without wrapping)
2. B's influence should be 10-30% of the final signal, never dominant
3. Use subindustry/industry neutralization for fundamental factors
4. Low-frequency fields (fundamental, mdf_*, fnd6_*) should use ts_rank with 126/252 day windows
5. Do NOT use short windows (5/10/21) on fundamental or MDF fields — they update quarterly
6. Avoid turnover > 50%. Use hump(), ts_decay_linear, or ts_target_tvr_decay for smoothing
7. The final expression must be valid WorldQuant Fast Expression syntax
8. When using mdf_* or fnd6_* fields, always wrap in rank() or group_rank() to avoid weight concentration
9. **OPERATOR BUDGET ≤ 64**: WorldQuant rejects expressions with more than 64 operators (each function call like rank, ts_rank, group_neutralize, if_else, +, -, *, / counts as one operator). Keep the expression compact — prefer 2-4 layers of nesting over deeply chained transforms. If a hybrid is getting long, drop a redundant rank() or fold two ts_* calls into one.

## Known Failure Patterns (AVOID THESE)
- Adding rank(-ts_decay_linear(returns, 5)) blindly — high self-correlation with existing alphas
- trade_when as a correlation/performance fix — it often just reduces samples
- revenue/cap, ebitda/cap, retained_earnings/cap — weak predictors
- Short ts_delta on quarterly fields — produces noise
- Weight concentration from unbounded ratios — always wrap in rank() or group_rank()
"""


def _build_generation_prompt(
    parent_a: str,
    parent_b: str,
    tag_pair: str,
    mutation_mode: str,
    feedback_context: str = "",
) -> str:
    """Build the user prompt for Gemini."""

    mode_desc = MUTATION_MODES.get(mutation_mode, "Use your best judgment for hybridization.")

    prompt = f"""## Parent Expressions

**Parent A (Primary Signal):** `{parent_a}`
**Parent B (Weak Modifier):** `{parent_b}`
**Tag Pair:** {tag_pair}

## Mutation Mode: {mutation_mode}
{mode_desc}

"""
    if feedback_context:
        prompt += f"""## Feedback from Previous Rounds
{feedback_context}

"""

    prompt += """## Output Format
Return ONLY a JSON object with these fields:
```json
{
    "expression": "your_hybrid_alpha_expression",
    "hypothesis": "one sentence economic rationale for why this hybrid should work",
    "mutation_mode": "the mode you used",
    "confidence": 0.0 to 1.0
}
```

Generate ONE hybrid expression. Be creative but disciplined.
"""
    return prompt


class GeminiHybridizer:
    """
    Uses Gemini to generate hybrid alpha candidates.

    Supports multiple mutation modes and feedback-guided generation.
    """

    def __init__(
        self,
        api_key: Optional[str] = None,
        model_name: str = "gemini-2.5-flash",
        temperature: float = 0.8,
    ):
        self.api_key = api_key or os.getenv("GEMINI_API_KEY")
        if not self.api_key:
            raise ValueError(
                "GEMINI_API_KEY not found. Set it in .env or pass directly."
            )

        self.model_name = model_name
        self.temperature = temperature
        self._client = None
        self._init_client()

    def _init_client(self):
        """Initialize Gemini client using the new google.genai SDK."""
        try:
            from google import genai
            self._client = genai.Client(api_key=self.api_key)
            logger.info(f"🤖 Gemini client initialized: {self.model_name}")
        except Exception as e:
            logger.error(f"Failed to initialize Gemini: {e}")
            raise

    def generate_hybrid(
        self,
        parent_a: str,
        parent_b: str,
        tag_pair: str,
        pair_id: str,
        mutation_mode: str = "mild_corr_breaker",
        feedback_context: str = "",
        max_retries: int = 2,
    ) -> Optional[HybridCandidate]:
        """
        Generate a single hybrid candidate using Gemini.

        Args:
            parent_a: Primary signal expression.
            parent_b: Weak modifier expression.
            tag_pair: e.g. "fundamental+price"
            pair_id: Pair identifier.
            mutation_mode: One of MUTATION_MODES keys.
            feedback_context: Context from previous failures/successes.
            max_retries: Max LLM call retries.

        Returns:
            HybridCandidate or None if generation fails.
        """
        from google import genai
        from google.genai import types

        prompt = _build_generation_prompt(
            parent_a, parent_b, tag_pair, mutation_mode, feedback_context
        )

        for attempt in range(max_retries):
            try:
                logger.info(
                    f"   🔄 Calling Gemini [{mutation_mode}] "
                    f"(attempt {attempt+1}/{max_retries})..."
                )

                response = self._client.models.generate_content(
                    model=self.model_name,
                    contents=prompt,
                    config=types.GenerateContentConfig(
                        system_instruction=SYSTEM_PROMPT,
                        temperature=self.temperature,
                        max_output_tokens=8192,
                    ),
                )

                raw_text = response.text
                logger.info(f"   📝 Got response ({len(raw_text)} chars)")

                # Extract JSON from response
                parsed = self._parse_response(raw_text)
                if parsed is None:
                    logger.warning(
                        f"   ⚠️ Failed to parse JSON from response, retrying..."
                    )
                    logger.debug(f"   Raw response: {raw_text[:200]}")
                    continue

                candidate = HybridCandidate(
                    expression=parsed["expression"],
                    mutation_mode=parsed.get("mutation_mode", mutation_mode),
                    hypothesis=parsed.get("hypothesis", ""),
                    parent_a_expr=parent_a,
                    parent_b_expr=parent_b,
                    tag_pair=tag_pair,
                    pair_id=pair_id,
                    raw_llm_response=raw_text,
                )

                # Basic validation
                if self._validate_expression(candidate.expression):
                    logger.info(
                        f"   ✅ Generated: {candidate.expression[:80]}..."
                    )
                    return candidate
                else:
                    logger.warning(
                        f"   ⚠️ Invalid expression: {candidate.expression[:60]}..."
                    )

            except Exception as e:
                logger.warning(f"   ❌ Gemini API error (attempt {attempt+1}): {e}")
                time.sleep(2 ** attempt)

        logger.error(f"   ❌ Failed to generate hybrid after {max_retries} attempts")
        return None

    def generate_batch(
        self,
        parent_a: str,
        parent_b: str,
        tag_pair: str,
        pair_id: str,
        modes: Optional[List[str]] = None,
        feedback_context: str = "",
    ) -> List[HybridCandidate]:
        """Generate multiple candidates using different mutation modes."""
        if modes is None:
            modes = list(MUTATION_MODES.keys())

        logger.info(
            f"   📦 Generating batch for pair {pair_id} "
            f"with {len(modes)} modes: {modes}"
        )

        candidates = []
        for i, mode in enumerate(modes):
            logger.info(f"   [{i+1}/{len(modes)}] Mode: {mode}")
            candidate = self.generate_hybrid(
                parent_a, parent_b, tag_pair, pair_id,
                mutation_mode=mode,
                feedback_context=feedback_context,
            )
            if candidate:
                candidates.append(candidate)
            time.sleep(1)  # Rate limiting

        logger.info(f"   📦 Batch complete: {len(candidates)}/{len(modes)} succeeded")
        return candidates

    @staticmethod
    def _parse_response(text: str) -> Optional[Dict[str, Any]]:
        """Extract JSON from LLM response text, handling truncated output."""
        # Try to find JSON block in code fence
        json_match = re.search(r'```(?:json)?\s*(\{.*?\})\s*```', text, re.DOTALL)
        if json_match:
            try:
                return json.loads(json_match.group(1))
            except json.JSONDecodeError:
                pass

        # Try raw JSON with "expression" key
        json_match = re.search(r'\{[^{}]*"expression"[^{}]*\}', text, re.DOTALL)
        if json_match:
            try:
                return json.loads(json_match.group())
            except json.JSONDecodeError:
                pass

        # Try any JSON object
        json_match = re.search(r'\{.*\}', text, re.DOTALL)
        if json_match:
            try:
                return json.loads(json_match.group())
            except json.JSONDecodeError:
                pass

        # Handle truncated JSON — try to extract expression field directly
        expr_match = re.search(
            r'"expression"\s*:\s*"([^"]+)"', text
        )
        if expr_match:
            result = {"expression": expr_match.group(1)}
            hyp_match = re.search(
                r'"hypothesis"\s*:\s*"([^"]+)"', text
            )
            if hyp_match:
                result["hypothesis"] = hyp_match.group(1)
            mode_match = re.search(
                r'"mutation_mode"\s*:\s*"([^"]+)"', text
            )
            if mode_match:
                result["mutation_mode"] = mode_match.group(1)
            logger.info(f"   🔧 Recovered expression from truncated JSON")
            return result

        return None

    @staticmethod
    def _validate_expression(expr: str) -> bool:
        """Basic validation of a WorldQuant expression."""
        if not expr or len(expr) < 5:
            return False

        # Check for balanced parentheses
        depth = 0
        for c in expr:
            if c == '(':
                depth += 1
            elif c == ')':
                depth -= 1
            if depth < 0:
                return False
        if depth != 0:
            return False

        # Must contain at least one WQ operator or field
        known_patterns = [
            "rank", "ts_rank", "group_rank", "ts_delta", "ts_mean",
            "ts_decay_linear", "ts_zscore", "group_neutralize",
            "if_else", "trade_when", "ts_sum", "ts_corr",
            "close", "open", "high", "low", "volume", "vwap", "returns",
        ]
        expr_lower = expr.lower()
        if not any(p in expr_lower for p in known_patterns):
            return False

        return True
